Fix submission generation github action

diff --git a/.github/workflows/test-cm-based-submission-generation.yml b/.github/workflows/test-cm-based-submission-generation.yml
--- a/.github/workflows/test-cm-based-submission-generation.yml
+++ b/.github/workflows/test-cm-based-submission-generation.yml
@@ -82,17 +82,23 @@ jobs:
         echo "::group::$description"
         cm ${{ matrix.action }} script --tags=generate,inference,submission  --clean --preprocess_submission=yes --results_dir=$PWD/submission_generation_tests/${{ matrix.case }}/ --run-checker --submitter=MLCommons --tar=yes --env.CM_TAR_OUTFILE=submission.tar.gz --division=${{ matrix.division }} --env.CM_DETERMINE_MEMORY_CONFIGURATION=yes --quiet $extra_run_args
         exit_status=$?
+        exit $? || echo "STEP_FAILED=true" >> $GITHUB_ENV
         echo "Exit status for the job ${description} ${exit_status}"
         if [[ "${{ matrix.case }}" == "case-5" || "${{ matrix.case }}" == "case-6" ]]; then
           # For cases 5 and 6, exit status should be 0 if cm command fails, 1 if it succeeds
           if [[ ${exit_status} -ne 0 ]]; then
-            exit 0
+            echo "STEP_FAILED=false" >> $GITHUB_ENV
           else
-            exit ${exit_status}
+            echo "STEP_FAILED=true" >> $GITHUB_ENV
           fi
         else
           # For other cases, exit with the original status
-          test ${exit_status} -eq 0 || exit ${exit_status}
+          test ${exit_status} -eq 0 || echo "STEP_FAILED=true" >> $GITHUB_ENV
         fi
         echo "::endgroup::"
+    - name: Fail if Step Failed
+      if: env.STEP_FAILED == 'true'
+      run: |
+        echo "Manually failing the workflow because the step failed."
+        exit 1
   
